unbind C-b
set -g prefix C-a

set -g mouse on
set -g focus-events

set -g status-position top
set -g status-justify absolute-centre
# set -g status-style "fg=white"
set -g status-style "bg=default"
# set -g status-left "[#{session_name}]"
# set -g status-right "#[fg=green]#H"
set -g status-right ""
set -g set-titles on
set -g set-titles-string "#S:#I:#W"

set -g message-style "fg=red"
setw -g monitor-activity off
set -g visual-activity off

setw -g mode-keys vi
set -g status-keys vi
set -g repeat-time 200

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows
set -g aggressive-resize

set -g pane-border-style "fg=#171717"
set -g pane-active-border-style "fg=#171717"

bind r source-file $HOME/.config/tmux/tmux.conf \; display "Config reloaded"

bind C-a last-window
bind -n C-b send-prefix

bind C-o neww "to $(fp)" # See ~/.local/bin/{fp,to}
bind G neww -n "lazygit" lazygit || cd master && lazygit

bind -r x kill-pane
bind y setw synchronize-panes

bind | split-window -h
bind "\\" split-window -h
bind "C-\\" split-window -h
bind - split-window -v
bind _ split-window -v

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r C-h resize-pane -L 2
bind -r C-j resize-pane -D 2
bind -r C-k resize-pane -U 2
bind -r C-l resize-pane -R 2
